# Numpy Introduction

In [49]:
import numpy as np
print np.__version__

1.9.2


## Numpy Array
In Numpy arrays are the main type of objects. In arrays elements are arranged in multidimensional tables. Array elements are indexed by positive integers, starting at 0.
### Create a numpy array
Create a 1-dimensional array and access its type, number of dimensions and shape and size:

In [50]:
A=np.array([1,2,3.0])
print A
print "Type of variable:     ",type(A)
print "Type of elements:     ",A.dtype
print "Number of dimensions: ",A.ndim
print "Shape:                ",A.shape
print "Size:                 ",A.size

[ 1.  2.  3.]
Type of variable:      <type 'numpy.ndarray'>
Type of elements:      float64
Number of dimensions:  1
Shape:                 (3L,)
Size:                  3


Create a 2-dimensional array and access its type, number of dimensions and shape and size:

In [51]:
B=np.array([[1,2,3,4],[5,6,0,1],[1,2,0,1]])
print B
print "Type of variable:     ",type(B)
print "Type of elements:     ",B.dtype
print "Number of dimensions: ",B.ndim
print "Shape:                ",B.shape
print "Size:                 ",B.size

[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]
Type of variable:      <type 'numpy.ndarray'>
Type of elements:      int32
Number of dimensions:  2
Shape:                 (3L, 4L)
Size:                  12


Create 2-dimensional array of zeros:

In [52]:
Z=np.zeros((5,2))
print Z

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


Create a 3-dimensional array of ones

In [53]:
O=np.ones((2,3,4))
print O

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]


Create 2-dimensional array of random integers between 10 (inclusive) and 20 (exclusive)

In [54]:
RI=np.random.randint(10,20,(5,3))
print RI

[[17 17 13]
 [12 16 18]
 [12 10 13]
 [19 19 14]
 [18 12 11]]


Create a 2-dimensional array of random numbers according to a Gaussian normal distribution with mean 0 and standard deviation 1.

In [55]:
RN=np.random.randn(2,5)
print RN

[[ 0.77 -0.26 -0.18  1.43 -0.23]
 [-0.99  1.47  0.24 -0.49  0.52]]


Create a 2-dimensional array of random numbers according to a Gaussian normal distribution with mean m=100 and standard deviation s=5.

In [56]:
mean=100
sigma=5
RN100=sigma*np.random.randn(4,8)+mean
print RN100

[[  88.01   95.01  104.52   96.19   87.87  106.71  105.     95.83]
 [  99.94   94.07   98.05  105.2    97.55   98.95   94.13   96.02]
 [  98.12  101.69   97.79  106.64  100.89   98.89   98.96  101.11]
 [ 104.48   93.26  103.99   94.45   97.67   88.25   99.96  105.28]]


Set print options, such that only 2 positions after the decimal point are printed.

In [57]:
np.set_printoptions(precision=2)
print RN100

[[  88.01   95.01  104.52   96.19   87.87  106.71  105.     95.83]
 [  99.94   94.07   98.05  105.2    97.55   98.95   94.13   96.02]
 [  98.12  101.69   97.79  106.64  100.89   98.89   98.96  101.11]
 [ 104.48   93.26  103.99   94.45   97.67   88.25   99.96  105.28]]


Throw a balanced dice for 30 times. The first element of the resulting array is the number of times a 1 has been thrown, the last element is the number of times a 1 has been thrown.   

In [58]:
RM=np.random.multinomial(30,[1/6.]*6)
print RM

[6 5 6 3 4 6]


Create a 1-dimensional array, containing a sequence of numbers, starting from 2, terminating before 18 and a stepzize of 4.  

In [109]:
S=np.arange(2,18,4)
print S

[ 2  6 10 14]


Reshape the 1-dimensional array to a 2-dimensional array. Note that the number of elements in the original and the reshaped array must be equal.

In [110]:
SR = S.reshape((2,2))
print SR

[[ 2  6]
 [10 14]]


In the _reshape()_ function the last shape-element need not be specified. It is enough to place a _-1_ at the corresponding position. Then this shape-element is calculated from the other shape-elements and the number of elements in the array. Below another _reshape()_ is performed. Note that the result is a _2-dimensional array_ of 1 row and 4 columns. 

In [113]:
SRR=SR.reshape((1,-1))
print SRR

[[ 2  6 10 14]]


The _flatten()_ function yields a _1-dimensional_ array.

In [114]:
SRRR=SR.flatten()
print SRRR

[ 2  6 10 14]


### Accessing Array Elements

In [61]:
print B

[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]


Access the element in the first row and third column:

In [62]:
b=B[0,2]
print b

3


Access the second row:

In [63]:
r=B[1,:]
print r

[5 6 0 1]


Access the first column:

In [64]:
c=B[:,0]
print c

[1 5 1]


Access elements 2 and 3 of the second column:

In [65]:
p=B[1,1:3]
print p

[6 0]


Access the lower right (2x2) subarray of B:

In [95]:
l=B[1:,2:]
print l

[[1 1]
 [1 1]]


Negative integers can be applied to access array elements in the reverse order. E.g. B[-1,:] is the last row of B. Thus the lower right (2x2) subarray of B can also be obtained by:

In [96]:
l2=B[-2:,-2:]
print l2

[[1 1]
 [1 1]]


Reversing columns and rows in an array:

In [101]:
RB=B[::-1,::-1]
print "B=\n",B
print "Reverse order of columns and rows:\nRB=\n",RB

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
Reverse order of columns and rows:
RB=
[[1 1 2 1]
 [1 1 6 5]
 [4 3 2 1]]


In [168]:
a=10*np.arange(10)
idx=np.array([1,9,3])
print a
print a[idx]

[ 0 10 20 30 40 50 60 70 80 90]
[10 90 30]


### Copying and Editing Array Elements

Copy B to CB:

In [67]:
CB=B
print CB

[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]


Editing part of B:

In [68]:
B[1:,2:]=np.zeros((2,2))
print "B=\n",B
print "CB=\n",CB

B=
[[1 2 3 4]
 [5 6 0 0]
 [1 2 0 0]]
CB=
[[1 2 3 4]
 [5 6 0 0]
 [1 2 0 0]]


As shown above copying by __=__ is a shallow copy. A **deep copy** can be implemented as follows:

In [69]:
CB=B.copy()
B[1:,2:]=np.ones((2,2))
print "B=\n",B
print "CB=\n",CB

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
CB=
[[1 2 3 4]
 [5 6 0 0]
 [1 2 0 0]]


## Basic Operations

### Add and multiply array elements with a scalar

In [70]:
print B

[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [71]:
print 3*B

[[ 3  6  9 12]
 [15 18  3  3]
 [ 3  6  3  3]]


In [72]:
print 100+B

[[101 102 103 104]
 [105 106 101 101]
 [101 102 101 101]]


### Elementwise addition and multiplication of matrices of the same size

In [73]:
A=np.random.randint(0,7,B.shape)
print "B=\n",B
print "A=\n",A

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
A=
[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


In [74]:
S=A+B
print S

[[ 3  5  5 10]
 [ 7  6  7  5]
 [ 1  6  6  6]]


In [75]:
P=A*B
print P

[[ 2  6  6 24]
 [10  0  6  4]
 [ 0  8  5  5]]


### Some other elementwise operations:

In [76]:
P2=B**2
print "All elements of B raised to a power of 2\n P2=\n",P2

All elements of B raised to a power of 2
 P2=
[[ 1  4  9 16]
 [25 36  1  1]
 [ 1  4  1  1]]


In [77]:
SR=np.sqrt(B)
print "Elementwise squareroot\n SR=\n",SR

Elementwise squareroot
 SR=
[[ 1.    1.41  1.73  2.  ]
 [ 2.24  2.45  1.    1.  ]
 [ 1.    1.41  1.    1.  ]]


In [78]:
SI=np.sin(B)
print "Elementwise sine\n SI=\n",SI

Elementwise sine
 SI=
[[ 0.84  0.91  0.14 -0.76]
 [-0.96 -0.28  0.84  0.84]
 [ 0.84  0.91  0.84  0.84]]


### Dot product

In [79]:
a=np.arange(3)
b=np.array([2,4,1])
print a
print b

[0 1 2]
[2 4 1]


In [80]:
c=np.dot(a,b)
print c

6


### Matrix multiplication

In [85]:
print "B=\n",B
print "A=\n",A

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
A=
[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


In [82]:
C=np.dot(A,B)
print "C=\n",C

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [84]:
BT=np.transpose(B)
print "BT=\n",BT
C=np.dot(A,BT)
print "C=\n",C

BT=
[[1 5 1]
 [2 6 2]
 [3 1 1]
 [4 1 1]]
C=
[[38 36 16]
 [36 20 12]
 [43 34 18]]


In [86]:
BT2=A.dot(BT)
print "BT2=\n",BT2

BT2=
[[38 36 16]
 [36 20 12]
 [43 34 18]]


### Simple statistic operations on arrays

In [87]:
print "A=\n",A 

A=
[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


In [90]:
print "Minimum = %3d\nMaximum = %3d\nMean = %3.2f"%(A.min(),A.max(),A.mean())

Minimum =   0
Maximum =   6
Mean = 3.25


In [92]:
print "Minimum = %s\nMaximum = %s\nMean = %s"%(A.min(axis=0),A.max(axis=0),A.mean(axis=0))

Minimum = [0 0 2 4]
Maximum = [2 4 6 6]
Mean = [ 1.33  2.33  4.33  5.  ]


In [93]:
print "Minimum = %s\nMaximum = %s\nMean = %s"%(A.min(axis=1),A.max(axis=1),A.mean(axis=1))

Minimum = [2 0 0]
Maximum = [6 6 5]
Mean = [ 3.25  3.    3.5 ]


## Stacking and splitting arrays 

In [115]:
print "A=\n",A
print "B=\n",B

A=
[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]
B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [116]:
V=np.vstack((A,B))
print "V=\n",V

V=
[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]
 [1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [117]:
H=np.hstack((A,B))
print "H=\n",H

H=
[[2 3 2 6 1 2 3 4]
 [2 0 6 4 5 6 1 1]
 [0 4 5 5 1 2 1 1]]


In [125]:
Hs=np.hsplit(H,(3,5))
print "1st part=\n",Hs[0]
print "2nd part=\n",Hs[1]
print "3rd part=\n",Hs[2]

1st part=
[[2 3 2]
 [2 0 6]
 [0 4 5]]
2nd part=
[[6 1]
 [4 5]
 [5 1]]
3rd part=
[[2 3 4]
 [6 1 1]
 [2 1 1]]


In [130]:
Vs=np.vsplit(V,(2,))
print "1st part=\n",Vs[0]
print "2nd part=\n",Vs[1]

1st part=
[[2 3 2 6]
 [2 0 6 4]]
2nd part=
[[0 4 5 5]
 [1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


## Ordering array elements

In [158]:
b=np.random.randint(0,100,15)
print b

[ 4 95 20 56 10 64  0 97 10 25 99 26 53 46 61]


In [162]:
bs=np.sort(b)
print bs

[ 0  4 10 10 20 25 26 46 53 56 61 64 95 97 99]
[ 4 95 20 56 10 64  0 97 10 25 99 26 53 46 61]


In [163]:
sortIdx=np.argsort(b)
print sortIdx

[ 6  0  4  8  2  9 11 13 12  3 14  5  1  7 10]


In [164]:
bss=b[sortIdx]
print bss

[ 0  4 10 10 20 25 26 46 53 56 61 64 95 97 99]


## Array Query

In [137]:
print A

[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


In [138]:
print A.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 2, 3, 1, 2, 3], dtype=int64))


In [136]:
print np.where(A>2)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64), array([1, 3, 2, 3, 1, 2, 3], dtype=int64))


In [135]:
print np.where(A>2,np.ones(A.shape),np.zeros(A.shape))

[[ 0.  1.  0.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  1.  1.  1.]]


In [132]:
print A

[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


In [140]:
print B

[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [141]:
print A>B

[[ True  True False  True]
 [False False  True  True]
 [False  True  True  True]]


In [142]:
print np.any(A>B,axis=0)

[ True  True  True  True]


In [143]:
print np.any(A>B,axis=1)

[ True  True  True]


In [144]:
print np.all(A>B,axis=0)

[False False False  True]


In [145]:
print np.all(A>B,axis=1)

[False False False]


## Import and Export Data from/to Files 

In [169]:
print A

[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


Save array A to a binary file in NumPy .npy format. In the example below the file is saved in the working directory. However, an arbitrary path can be specified in the string-parameter of _save()_.

In [170]:
np.save("binFileA",A)

Load array, which has been saved to a binary file into NumPy:

In [173]:
AL=np.load("binFileA.npy")
print AL

[[2 3 2 6]
 [2 0 6 4]
 [0 4 5 5]]


Save array to a text-file. Note that _savetxt()_ also has parameters for separating columns (_delimiter=''_) and lines (_newline='\n'_). Thus this method and the corresponding _loadtxt()_-method can also be applied for writing to and reading from .csv.

Load data from a textfile into a NumPy array:

In [179]:
np.savetxt("textFileA",A,fmt="%4.2f")

In [181]:
AT=np.loadtxt("textFileA")
print AT

[[ 2.  3.  2.  6.]
 [ 2.  0.  6.  4.]
 [ 0.  4.  5.  5.]]


## Exercises